version: '3.8'

services:
  tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    command: ["python3", "tracker.py"]  # Asegúrate de ejecutar tracker.py
    restart: always

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50001:50001"
    depends_on:
      - tracker
    command: ["sh", "-c", "sleep 5; python3 server.py"]

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50002:50002"
    depends_on:
      - tracker
    command: ["sh", "-c", "sleep 5; python3 server.py"]

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50003:50003"
    depends_on:
      - tracker
    command: ["sh", "-c", "sleep 5; python3 server.py"]

  node4:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50004:50004"
    depends_on:
      - tracker
    command: ["sh", "-c", "sleep 5; python3 server.py"]
