version: '3'
services:
  sr0263-tracker:
    image: sr0263-tracker
    ports:
      - "50052:50052"
  
  sr0263-node1:
    image: sr0263-node1
    ports:
      - "50001:50001"
    depends_on:
      - sr0263-tracker

  sr0263-node2:
    image: sr0263-node2
    ports:
      - "50002:50002"
    depends_on:
      - sr0263-tracker

  sr0263-node3:
    image: sr0263-node3
    ports:
      - "50003:50003"
    depends_on:
      - sr0263-tracker

  sr0263-node4:
    image: sr0263-node4
    ports:
      - "50004:50004"
    depends_on:
      - sr0263-tracker
