version: '3.8'

services:
  tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50052:50052"

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50001:50001"
    depends_on:
      - tracker

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50002:50002"
    depends_on:
      - tracker

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50003:50003"
    depends_on:
      - tracker

  node4:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50004:50004"
    depends_on:
      - tracker
