# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p2p.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'p2p.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tp2p.proto\"7\n\x0bJoinRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x17\n\x0f\x61vailable_files\x18\x02 \x03(\t\"\x1f\n\x0cJoinResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cLeaveRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\" \n\rLeaveResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0eGetFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"4\n\x0fGetFileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x66iledata\x18\x02 \x01(\x0c\"4\n\x0ePutFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08\x66iledata\x18\x02 \x01(\x0c\"3\n\x0fPutFileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x11ListNodesResponse\x12\x11\n\taddresses\x18\x01 \x03(\t\"\x07\n\x05\x45mpty2\xed\x01\n\x0bPeerService\x12*\n\x0bJoinNetwork\x12\x0c.JoinRequest\x1a\r.JoinResponse\x12-\n\x0cLeaveNetwork\x12\r.LeaveRequest\x1a\x0e.LeaveResponse\x12,\n\x07GetFile\x12\x0f.GetFileRequest\x1a\x10.GetFileResponse\x12,\n\x07PutFile\x12\x0f.PutFileRequest\x1a\x10.PutFileResponse\x12\'\n\tListNodes\x12\x06.Empty\x1a\x12.ListNodesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINREQUEST']._serialized_start=13
  _globals['_JOINREQUEST']._serialized_end=68
  _globals['_JOINRESPONSE']._serialized_start=70
  _globals['_JOINRESPONSE']._serialized_end=101
  _globals['_LEAVEREQUEST']._serialized_start=103
  _globals['_LEAVEREQUEST']._serialized_end=134
  _globals['_LEAVERESPONSE']._serialized_start=136
  _globals['_LEAVERESPONSE']._serialized_end=168
  _globals['_GETFILEREQUEST']._serialized_start=170
  _globals['_GETFILEREQUEST']._serialized_end=204
  _globals['_GETFILERESPONSE']._serialized_start=206
  _globals['_GETFILERESPONSE']._serialized_end=258
  _globals['_PUTFILEREQUEST']._serialized_start=260
  _globals['_PUTFILEREQUEST']._serialized_end=312
  _globals['_PUTFILERESPONSE']._serialized_start=314
  _globals['_PUTFILERESPONSE']._serialized_end=365
  _globals['_LISTNODESRESPONSE']._serialized_start=367
  _globals['_LISTNODESRESPONSE']._serialized_end=405
  _globals['_EMPTY']._serialized_start=407
  _globals['_EMPTY']._serialized_end=414
  _globals['_PEERSERVICE']._serialized_start=417
  _globals['_PEERSERVICE']._serialized_end=654
# @@protoc_insertion_point(module_scope)
